spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100GB
      max-request-size: 100GB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/files
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 1488

